# Generated by Django 5.2.6 on 2025-09-13 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0002_menuitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
